listen: :443

tls:
  acme:
    domains:
      - vpn.example.com
    email: your@email.com
    disable_http_challenge: true

auth:
  type: file
  file:
    path: /etc/hysteria/users.yaml

masquerade:
  type: proxy
  proxy:
    url: https://www.cloudflare.com