listen: :443

acme:
  domains:
    - vpn.example.com
  email: your@email.com
  disable_http_challenge: true

auth:
  type: userpass
  userpass:
    user1: pass1
    user2: pass2
    user3: pass3

masquerade:
  type: proxy
  proxy:
    url: https://www.xbox.com
    rewriteHost: true
